#!/bin/sh
# SessionBox container entrypoint.
#
# The container starts as root only to prepare sshd and then execs the CMD.
# Agent commands always run as the non-root "agent" user.
set -eu

# Inject the ephemeral public key generated by SessionBox for this container.
if [ -n "${SESSIONBOX_AUTHORIZED_KEY:-}" ]; then
  install -d -m 700 -o agent -g agent /home/agent/.ssh
  printf '%s\n' "${SESSIONBOX_AUTHORIZED_KEY}" > /home/agent/.ssh/authorized_keys
  chown agent:agent /home/agent/.ssh/authorized_keys
  chmod 600 /home/agent/.ssh/authorized_keys
fi

# Unique SSH host key per container, generated on first start.
if [ ! -f /etc/ssh/ssh_host_ed25519_key ]; then
  ssh-keygen -A
fi

mkdir -p /run/sshd

exec "$@"
